version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    # Opcional: montar volumen para desarrollo hot-reload
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
